export interface WcagRef {
  sc: string;
  level: 'A' | 'AA' | 'AAA';
}

export const AXE_RULE_TO_WCAG: Record<string, WcagRef> = {
  'area-alt': { sc: '1.1.1', level: 'A' },
  'aria-allowed-attr': { sc: '4.1.2', level: 'A' },
  'aria-allowed-role': { sc: '4.1.2', level: 'A' },
  'aria-hidden-body': { sc: '4.1.2', level: 'A' },
  'aria-hidden-focus': { sc: '4.1.2', level: 'A' },
  'aria-input-field-name': { sc: '4.1.2', level: 'A' },
  'aria-required-attr': { sc: '4.1.2', level: 'A' },
  'aria-required-children': { sc: '1.3.1', level: 'A' },
  'aria-required-parent': { sc: '1.3.1', level: 'A' },
  'aria-roles': { sc: '4.1.2', level: 'A' },
  'aria-toggle-field-name': { sc: '4.1.2', level: 'A' },
  'aria-valid-attr-value': { sc: '4.1.2', level: 'A' },
  'aria-valid-attr': { sc: '4.1.2', level: 'A' },
  'autocomplete-valid': { sc: '1.3.5', level: 'AA' },
  'avoid-inline-spacing': { sc: '1.4.12', level: 'AA' },
  'button-name': { sc: '4.1.2', level: 'A' },
  'bypass': { sc: '2.4.1', level: 'A' },
  'color-contrast': { sc: '1.4.3', level: 'AA' },
  'definition-list': { sc: '1.3.1', level: 'A' },
  'dlitem': { sc: '1.3.1', level: 'A' },
  'document-title': { sc: '2.4.2', level: 'A' },
  'duplicate-id-aria': { sc: '4.1.1', level: 'A' },
  'duplicate-id': { sc: '4.1.1', level: 'A' },
  'empty-heading': { sc: '1.3.1', level: 'A' },
  'form-field-multiple-labels': { sc: '3.3.2', level: 'A' },
  'frame-title': { sc: '4.1.2', level: 'A' },
  'heading-order': { sc: '1.3.1', level: 'A' },
  'html-has-lang': { sc: '3.1.1', level: 'A' },
  'html-lang-valid': { sc: '3.1.1', level: 'A' },
  'html-xml-lang-mismatch': { sc: '3.1.1', level: 'A' },
  'image-alt': { sc: '1.1.1', level: 'A' },
  'input-button-name': { sc: '4.1.2', level: 'A' },
  'input-image-alt': { sc: '1.1.1', level: 'A' },
  'label': { sc: '3.3.2', level: 'A' },
  'landmark-one-main': { sc: '1.3.1', level: 'A' },
  'link-in-text-block': { sc: '1.4.1', level: 'A' },
  'link-name': { sc: '2.4.4', level: 'A' },
  'list': { sc: '1.3.1', level: 'A' },
  'listitem': { sc: '1.3.1', level: 'A' },
  'meta-refresh': { sc: '2.2.1', level: 'A' },
  'meta-viewport': { sc: '1.4.4', level: 'AA' },
  'nested-interactive': { sc: '4.1.2', level: 'A' },
  'object-alt': { sc: '1.1.1', level: 'A' },
  'page-has-heading-one': { sc: '1.3.1', level: 'A' },
  'region': { sc: '1.3.1', level: 'A' },
  'role-img-alt': { sc: '1.1.1', level: 'A' },
  'scrollable-region-focusable': { sc: '2.1.1', level: 'A' },
  'select-name': { sc: '4.1.2', level: 'A' },
  'server-side-image-map': { sc: '2.1.1', level: 'A' },
  'skip-link': { sc: '2.4.1', level: 'A' },
  'svg-img-alt': { sc: '1.1.1', level: 'A' },
  'tabindex': { sc: '2.4.3', level: 'A' },
  'table-duplicate-name': { sc: '1.3.1', level: 'A' },
  'target-size': { sc: '2.5.8', level: 'AA' },
  'td-headers-attr': { sc: '1.3.1', level: 'A' },
  'th-has-data-cells': { sc: '1.3.1', level: 'A' },
  'valid-lang': { sc: '3.1.2', level: 'AA' },
  'video-caption': { sc: '1.2.2', level: 'A' },
};

export const WCAG_ANCHOR_SLUGS: Record<string, string> = {
  '1.1.1': 'non-text-content',
  '1.2.1': 'audio-only-and-video-only-prerecorded',
  '1.2.2': 'captions-prerecorded',
  '1.2.3': 'audio-description-or-media-alternative-prerecorded',
  '1.2.4': 'captions-live',
  '1.2.5': 'audio-description-prerecorded',
  '1.3.1': 'info-and-relationships',
  '1.3.2': 'meaningful-sequence',
  '1.3.3': 'sensory-characteristics',
  '1.3.4': 'orientation',
  '1.3.5': 'identify-input-purpose',
  '1.4.1': 'use-of-color',
  '1.4.2': 'audio-control',
  '1.4.3': 'contrast-minimum',
  '1.4.4': 'resize-text',
  '1.4.5': 'images-of-text',
  '1.4.10': 'reflow',
  '1.4.11': 'non-text-contrast',
  '1.4.12': 'text-spacing',
  '1.4.13': 'content-on-hover-or-focus',
  '2.1.1': 'keyboard',
  '2.1.2': 'no-keyboard-trap',
  '2.1.4': 'character-key-shortcuts',
  '2.2.1': 'timing-adjustable',
  '2.2.2': 'pause-stop-hide',
  '2.3.1': 'three-flashes-or-below-threshold',
  '2.4.1': 'bypass-blocks',
  '2.4.2': 'page-titled',
  '2.4.3': 'focus-order',
  '2.4.4': 'link-purpose-in-context',
  '2.4.5': 'multiple-ways',
  '2.4.6': 'headings-and-labels',
  '2.4.7': 'focus-visible',
  '2.4.11': 'focus-not-obscured-minimum',
  '2.5.1': 'pointer-gestures',
  '2.5.2': 'pointer-cancellation',
  '2.5.3': 'label-in-name',
  '2.5.4': 'motion-actuation',
  '2.5.7': 'dragging-movements',
  '2.5.8': 'target-size-minimum',
  '3.1.1': 'language-of-page',
  '3.1.2': 'language-of-parts',
  '3.2.1': 'on-focus',
  '3.2.2': 'on-input',
  '3.2.3': 'consistent-navigation',
  '3.2.4': 'consistent-identification',
  '3.2.6': 'consistent-help',
  '3.3.1': 'error-identification',
  '3.3.2': 'labels-or-instructions',
  '3.3.3': 'error-suggestion',
  '3.3.4': 'error-prevention-legal-financial-data',
  '3.3.7': 'redundant-entry',
  '3.3.8': 'accessible-authentication-minimum',
  '4.1.2': 'name-role-value',
  '4.1.3': 'status-messages',
};

export function formatWcagCitation(ref: WcagRef): string {
  return `WCAG 2.2 SC ${ref.sc} (Level ${ref.level})`;
}

export function wcagUrl(sc: string): string | null {
  const slug = WCAG_ANCHOR_SLUGS[sc];
  return slug ? `https://www.w3.org/WAI/WCAG22/Understanding/${slug}.html` : null;
}
